### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by rodydavis** [luanpotter/vscode-dart-import#1]
`Current file is not on project root or not on lib folder? File must be on $root/lib.`

getting the error in any file I try to run the command in. 

Where do you run the command at what level of the project?

**Comment by rodydavis** [comment]
I am running it from my Flutter project not a Flutter plugin project.

**Comment by luanpotter** [comment]
Hi @AppleEducate, thanks a lot for your feedback!

Indeed there was a bug when the file was directly inside the lib folder. I fixed it on version 0.1.0, and just released the new version to the Marketplace.

Could you please update and verify if it's working now?

**Comment by rodydavis** [comment]
Just installed the updated and it worked perfectly, thank you!

Rody Davis Jr.
Full Stack Mobile Developer
Github | Website | Appstore | LinkedIn
Twitter | Facebook | YouTube
