### ISSUE TITLE
Get rid of notifications

### ISSUE THREAD

**Issue by JCKodel** [luanpotter/vscode-dart-import#16]
![image](https://user-images.githubusercontent.com/379339/78814583-3725a480-79a5-11ea-82da-a07637237c5b.png)

This is annoying.

![image](https://user-images.githubusercontent.com/379339/78814629-4c023800-79a5-11ea-9561-57cdd812667a.png)

**Comment by luanpotter** [comment]
Haha I like the feedback, the plugin my take a good second to run and I like to know it finished w/o errors. I'm open to a PR adding a setting to disable it :)

**Comment by luanpotter** [comment]
Fixed by #26, thanks @shiv-k-sharma
