### ISSUE TITLE
Fix imports for all files in project?

### ISSUE THREAD

**Issue by Prn-Ice** [luanpotter/vscode-dart-import#19]
Hi, how can I get it to organize all my dart files as opposed to just the file I'm working on.

**Comment by ninest** [comment]
Are there any updates to this? I have a project with over 20+ `.dart` files. It will be very useful if there was a command for "Fix ALL imports", which goes through all files and fixes imports

**Comment by joao-v-maia** [comment]
This would be a very cool feature, i will try to implement it but i've never worked with vscode extensions, is there anyone who would like to do this? 

Doesn't seems to be complicated, the fix proccess is already done, the new command just needs to iterate over all .dart files inside /lib, i'm just not sure about how vscode deals with write permissions and access over a bunch of files like that.

**Comment by ElZombieIsra** [comment]
Better late than never. 

I made a PR (#23) that implements this functionality but it lacks certain things that I need some help with. It would be very helpful if you can see the PR and you guys try to address this issues.

Thank you

**Comment by luanpotter** [comment]
I merged that and left some comments about the shortcomings :)
