### ISSUE TITLE
Run from commandline and pass path/file to it?

### ISSUE THREAD

**Issue by MostHated** [luanpotter/vscode-dart-import#20]
Hey there,
    I love this extension, but I primarily use the IntelliJ/Android Studio IDE, so as of now I keep VSCode open to my project and have it in the background while I work in IntelliJ/Android Studio then when I import something I alt tab and then open the file, run your extension, and that's that. It is definitely not ideal, though. 

I was wondering if there happens to be any way to be able to directly run this extension from the command line and just pass in the necessary parameters? 

Thanks,
-MH

**Comment by luanpotter** [comment]
I don't know if it's possible to run vs code extensions like that, my guess is no haha. what we could do is extract bits that independent to a package (code is pretty well divided into real logic and vscode interface for testing) and then make a node cli that uses that.still you would need to build all the file interface using node. then we would have the two options

**Comment by MostHated** [comment]
It's no worry, just after I posted this I decided to see if I could create my own using Dart as a standalone cli application, which was why I just went ahead and closed this. It came out extremely well.

**Comment by luanpotter** [comment]
@MostHated if you want to share, I can link your repo from here in case other people want to use it as CLI as well!

**Comment by MostHated** [comment]
Yeah man, sure thing.

https://github.com/instance-id/relative_imports

I hope you don't mind, I borrowed your Regex line, but I linked back to it in the source. 
https://github.com/instance-id/relative_imports/blob/bbd2f4331d0b89b29077b7c27dd8072544874736/bin/relative_imports.dart#L174

**Comment by luanpotter** [comment]
Not at all, I am glad you found the code useful :)
