### ISSUE TITLE
Support fixing imports in multi-project workspaces

### ISSUE THREAD

**Issue by shyndman** [luanpotter/vscode-dart-import#3]
Hi there,

I often open multiple projects at the same time, and I've found that your (incredibly useful) extension doesn't work in those cases.

Would you consider adding support for this use case?

**Comment by shyndman** [comment]
It seems like deriving the pubspec from the editor's currently active document might do the trick.

**Comment by luanpotter** [comment]
Hi, @shyndman ! Thanks a lot for your comment and feedback. Indeed that's a great catch I had not had. I think it'd be a nice addition. I can't look at this right away, but maybe soon I will. Looks to me like a relatively simple change. However, would you rather help out with a PR? I'd be glad to merge it in ;)

**Comment by shyndman** [comment]
Can do. Thanks @luanpotter :)

**Comment by shyndman** [comment]
I took a stab at it here. Looks like it's working, but I'm going to use it for a few days to put it through its paces.
https://github.com/shyndman/vscode-dart-import/commit/3a42c4c348dd4c63a20d0c4b8345f668efb1adce

**Comment by shyndman** [comment]
Didn't need a couple days. This seems to work well.

**Comment by luanpotter** [comment]
Deployed as 0.1.3 :)
