### ISSUE TITLE
Support for Windows machines

### ISSUE THREAD

**Issue by luanpotter** [luanpotter/vscode-dart-import#6]
The extension will not be able to process file paths correctly on Windows machines, because for some reason they uses inverted separators for file paths...

I believe there is a way in node to use the path module to construct the file paths in a way that's independent of the PATH_SEPARATOR. I'm not sure if it's available within vscode extension environment, but it believe it might.

It will, however, require changes in all the code that handles path to consider the case to have a weird path separator.

I don't own any windows systems (thankfully) to test this out, so if @runedrune or someone else would like to make a PR for this, I'd happily merge it. But I don't intend on working on this issue myself.

This problem emerged from a discussion on #2.

**Comment by ElZombieIsra** [comment]
I solved this issue in #10

**Comment by luanpotter** [comment]
Thanks, @ElZombieIsra , merged and released under `0.1.4`.

**Comment by fleepgeek** [comment]
@ElZombieIsra thanks for this

**Comment by ElZombieIsra** [comment]
@fleepgeek You're welcome. I'm glad this helps others.
Also thanks to @luanpotter for creating this awesome extension.

**Comment by fleepgeek** [comment]
Yeah true. He really did a great job.
Thanks for creating this extension @luanpotter
