### ISSUE TITLE
Add ability to auto run on file save

### ISSUE THREAD

**Issue by agordeev** [luanpotter/vscode-dart-import#7]
It'd be great if the command could run automatically when file is saved.

**Comment by luanpotter** [comment]
@agordeev isn't there a built in way to run command actions on save via preferences? Then you could run `dart-import.fix` command...

**Comment by agordeev** [comment]
Only if you install additional plugin I believe

**Comment by luanpotter** [comment]
In that case, we can have a configurable setting to allow that. Are you interested in providing a PR? :)

**Comment by luanpotter** [comment]
Fixed by #26, thanks @shiv-k-sharma
